apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-ordering-green
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-ordering
      version: green
  template:
    metadata:
      labels:
        app: food-ordering
        version: green
    spec:
      containers:
        - name: food-ordering
          image: sweetyraj22/food-ordering:latest   # Use same or new image
          ports:
            - containerPort: 80
