apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-ordering-blue
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-ordering
      version: blue
  template:
    metadata:
      labels:
        app: food-ordering
        version: blue
    spec:
      containers:
        - name: food-ordering
          image: sweetyraj22/food-ordering:latest  
          ports:
            - containerPort: 80

